import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="w-full border-b border-zinc-200 bg-white/80 backdrop-blur dark:border-zinc-800 dark:bg-black/60">
          <div className="mx-auto flex w-full max-w-6xl items-center gap-4 px-6 py-4">
            <Link
              href="/"
              className="text-sm font-semibold text-zinc-900 transition-colors hover:text-black dark:text-zinc-100 dark:hover:text-white"
            >
              Home
            </Link>
            <Link
              href="/manage"
              className="text-sm font-semibold text-zinc-900 transition-colors hover:text-black dark:text-zinc-100 dark:hover:text-white"
            >
              Manage Library
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
